#!/bin/sh

# This script helps document the credentials that need to be set up in n8n UI
# After the container starts, access http://localhost:5678 and configure these credentials:

echo "==================================================================="
echo "N8N CREDENTIALS SETUP GUIDE"
echo "==================================================================="
echo ""
echo "The workflow 'CV-Screening-bot' requires the following credentials:"
echo ""
echo "1. OpenRouter API (ID: HWw2jjaQs8KL289j)"
echo "   - Name: OpenRouter account"
echo "   - API Key: $OPENROUTER_API_KEY"
echo ""
echo "2. Google Drive OAuth2 API (ID: Ooz9BFztWbsjSQVc)"
echo "   - Name: Google Drive account"
echo "   - Client ID: $GOOGLE_DRIVE_CLIENT_ID"
echo "   - Client Secret: $GOOGLE_DRIVE_CLIENT_SECRET"
echo ""
echo "3. Gmail OAuth2 (ID: hG9W4VyQy4KBAUnx)"
echo "   - Name: Gmail account"
echo "   - Client ID: $GMAIL_CLIENT_ID"
echo "   - Client Secret: $GMAIL_CLIENT_SECRET"
echo ""
echo "4. Google Sheets OAuth2 API (ID: EcBm4OnVFrsju55I)"
echo "   - Name: Google Sheets account"
echo "   - Client ID: $GOOGLE_SHEETS_CLIENT_ID"
echo "   - Client Secret: $GOOGLE_SHEETS_CLIENT_SECRET"
echo ""
echo "5. HuggingFace API (ID: yCeTQMnkeeQ4aidD)"
echo "   - Name: HuggingFaceApi account"
echo "   - API Key: $HUGGINGFACE_API_KEY"
echo ""
echo "6. Pinecone API (ID: ZzroYu4mkdKJ1jss)"
echo "   - Name: PineconeApi account"
echo "   - API Key: $PINECONE_API_KEY"
echo "   - Environment: $PINECONE_ENVIRONMENT"
echo ""
echo "7. Telegram API (ID: 88BYzicBnLoNhTZ9)"
echo "   - Name: Telegram account"
echo "   - Access Token: $TELEGRAM_BOT_TOKEN"
echo ""
echo "==================================================================="
echo "SETUP INSTRUCTIONS:"
echo "==================================================================="
echo "1. Access n8n UI at: http://localhost:5678"
echo "2. Go to Settings > Credentials"
echo "3. Add each credential type listed above"
echo "4. Use the exact names and IDs shown"
echo "5. For OAuth credentials, you'll need to complete the OAuth flow"
echo ""
echo "==================================================================="
