apiVersion: v2
name: n8n
description: A Helm chart for n8n workflow automation tool
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - n8n
  - workflow
  - automation
maintainers:
  - name: Your Name
    email: your.email@example.com
